let mydate=new Date()
//console.log(mydate.toLocaleString())
//console.log(mydate.toString())
//console.log(mydate.toDateString())
//console.log(mydate.toISOString())
//console.log(typeof mydate)
let mycreateddate=new Date(2023,0,23,5,3)
//console.log(mycreateddate.toDateString())
//console.log(mycreateddate.toLocaleString())
let mydates=new Date("2023-01-14")
//console.log(mydates.toDateString())

//+++++++++++++++++++++++++++++++ TIME ++++++++++++++++++++++++++++++++++

let mytimestamp=Date.now()
console.log(mytimestamp)
console.log(mydates.getTime())


